
import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Search, ChevronRight, Star, Shield, Bot, CircleArrowRight } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ReviewCard from '@/components/ReviewCard';
import { cn } from '@/lib/utils';

// Mock data for demo purposes
const featuredReviews = [
  {
    id: '1',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    brief: 'Industry-leading noise cancellation with exceptional sound quality. Perfect for commuters and audiophiles alike.',
    commentsCount: 32,
    likesCount: 156,
    tags: ['Noise-Cancelling', 'Wireless', 'Premium']
  },
  {
    id: '2',
    title: 'Ember Temperature Control Smart Mug',
    category: 'Kitchen',
    image: 'https://images.unsplash.com/photo-1577937927133-66ef983cbe63?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    brief: 'Keep your coffee or tea at the perfect temperature from the first sip to the last drop with this app-controlled smart mug.',
    commentsCount: 18,
    likesCount: 87,
    tags: ['Smart Home', 'Tech Gadget', 'Coffee']
  },
  {
    id: '3',
    title: 'Dyson V15 Detect Cordless Vacuum',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    brief: 'Revolutionary cordless vacuum with laser detection to reveal invisible dust. Powerful suction and intelligent cleaning modes.',
    commentsCount: 24,
    likesCount: 112,
    tags: ['Cordless', 'Smart Tech', 'Cleaning']
  },
  {
    id: '4',
    title: 'Oura Ring Gen 3 - Health & Sleep Tracker',
    category: 'Wearables',
    image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    brief: 'Advanced health metrics and sleep tracking in a sleek, minimalist ring. Perfect for 24/7 health monitoring without the bulk.',
    commentsCount: 15,
    likesCount: 73,
    tags: ['Sleep Tracking', 'Health Tech', 'Wearable']
  },
  {
    id: '5',
    title: 'Kindle Paperwhite Signature Edition',
    category: 'Reading',
    image: 'https://images.unsplash.com/photo-1544631008-92692777a67b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    brief: 'The ultimate e-reader with a 6.8" display, wireless charging, and auto-adjusting front light for comfortable reading day or night.',
    commentsCount: 45,
    likesCount: 231,
    tags: ['E-reader', 'Waterproof', 'Long Battery']
  },
  {
    id: '6',
    title: 'Samsung 49" Odyssey G9 Gaming Monitor',
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    brief: 'Ultra-wide curved gaming monitor with stunning 5120x1440 resolution and 240Hz refresh rate for immersive gaming experience.',
    commentsCount: 29,
    likesCount: 142,
    tags: ['Ultra-wide', 'Gaming', 'High Refresh']
  }
];

const categories = [
  { name: 'Electronics', icon: '💻', count: 156 },
  { name: 'Home & Kitchen', icon: '🏠', count: 124 },
  { name: 'Fashion', icon: '👕', count: 98 },
  { name: 'Beauty', icon: '💄', count: 82 },
  { name: 'Books', icon: '📚', count: 145 },
  { name: 'Gaming', icon: '🎮', count: 73 },
  { name: 'Health & Fitness', icon: '💪', count: 67 },
  { name: 'Travel', icon: '✈️', count: 51 }
];

const HeroSection = () => (
  <div className="relative bg-gradient-to-b from-blue-50 to-transparent dark:from-gray-900 min-h-[90vh] flex items-center">
    <div className="container px-4 md:px-6 mx-auto pt-32 pb-16">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        <div className="space-y-8 staggered-fade">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              AI-Powered Reviews <br />
              <span className="text-primary">You Can Trust</span>
            </h1>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              Discover unbiased, data-driven reviews generated by advanced AI. No human bias, just factual analysis.
            </p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-4">
            <Button size="lg" className="transition-all duration-300 hover:scale-[1.02]">
              <Search className="mr-2 h-5 w-5" /> Explore Reviews
            </Button>
            <Button variant="outline" size="lg" asChild>
              <Link to="/how-it-works">
                How It Works <ChevronRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
          </div>
          
          <div className="flex items-center space-x-4">
            <div className="flex -space-x-2">
              <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                <Star className="h-5 w-5 text-primary" />
              </div>
              <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                <Shield className="h-5 w-5 text-primary" />
              </div>
              <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                <Bot className="h-5 w-5 text-primary" />
              </div>
            </div>
            <p className="text-sm text-muted-foreground">
              Trusted by <span className="font-medium text-foreground">10,000+</span> users
            </p>
          </div>
        </div>
        
        <div className="relative">
          <div className="absolute -inset-0.5 bg-gradient-to-r from-primary to-blue-400 rounded-xl blur-2xl opacity-10 animate-pulse"></div>
          <div className="relative glass rounded-xl overflow-hidden shadow-xl p-2 animate-fade-in">
            <img 
              src="https://images.unsplash.com/photo-1521791055366-0d553872125f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80" 
              alt="AI Review Process" 
              className="rounded-lg w-full h-full object-cover"
            />
            <div className="absolute bottom-0 left-0 right-0 glass p-4 backdrop-blur-md">
              <div className="flex items-center justify-between">
                <div>
                  <Badge className="mb-2">New Review</Badge>
                  <h3 className="font-medium">MacBook Pro M3 Max</h3>
                </div>
                <div className="flex text-yellow-400">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400" />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    {/* Abstract shapes */}
    <div className="hidden md:block absolute top-1/4 right-0 h-64 w-64 bg-primary/5 rounded-full blur-3xl"></div>
    <div className="hidden md:block absolute bottom-1/4 left-0 h-96 w-96 bg-blue-400/5 rounded-full blur-3xl"></div>
  </div>
);

const SearchSection = () => (
  <div className="container px-4 md:px-6 mx-auto py-12">
    <div className="glass mx-auto max-w-4xl p-8 rounded-xl shadow-sm">
      <div className="space-y-6">
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-semibold">Find the Perfect Product</h2>
          <p className="text-muted-foreground">Search for AI-generated reviews across all categories</p>
        </div>
        
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
          <Input 
            placeholder="Search for products, brands, or categories..." 
            className="pl-10 py-6 text-base"
          />
        </div>
        
        <div>
          <p className="mb-3 text-sm text-muted-foreground">Popular searches:</p>
          <div className="flex flex-wrap gap-2">
            {["Smartphones", "Laptops", "Headphones", "Smart Home", "Gaming", "Fitness Trackers"].map((term, i) => (
              <Badge key={i} variant="secondary" className="cursor-pointer hover:bg-secondary/80 transition-colors">
                {term}
              </Badge>
            ))}
          </div>
        </div>
      </div>
    </div>
  </div>
);

const FeaturedReviewsSection = () => (
  <div className="container px-4 md:px-6 mx-auto py-12">
    <div className="space-y-2 text-center mb-10">
      <h2 className="text-3xl font-bold tracking-tight">Featured Reviews</h2>
      <p className="text-muted-foreground max-w-[700px] mx-auto">
        Discover our latest AI-generated reviews across popular categories
      </p>
    </div>
    
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {featuredReviews.map((review) => (
        <div key={review.id} className="animate-fade-in" style={{ animationDelay: `${parseInt(review.id) * 100}ms` }}>
          <ReviewCard {...review} />
        </div>
      ))}
    </div>
    
    <div className="mt-12 text-center">
      <Button asChild>
        <Link to="/all-reviews">
          View All Reviews <ChevronRight className="ml-2 h-5 w-5" />
        </Link>
      </Button>
    </div>
  </div>
);

const CategoriesSection = () => (
  <div className="bg-secondary/50 py-16">
    <div className="container px-4 md:px-6 mx-auto">
      <div className="space-y-2 text-center mb-10">
        <h2 className="text-3xl font-bold tracking-tight">Browse by Category</h2>
        <p className="text-muted-foreground max-w-[700px] mx-auto">
          Find AI-generated reviews in your preferred product categories
        </p>
      </div>
      
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
        {categories.map((category, i) => (
          <Link 
            to={`/category/${category.name.toLowerCase().replace(/\s+/g, '-')}`}
            key={i} 
            className={cn(
              "group glass flex items-center p-4 rounded-xl transition-all duration-300",
              "hover:shadow-md hover:scale-[1.02]"
            )}
          >
            <div className="w-10 h-10 flex items-center justify-center rounded-full bg-primary/10 mr-3 text-xl">
              {category.icon}
            </div>
            <div>
              <h3 className="font-medium group-hover:text-primary transition-colors">{category.name}</h3>
              <p className="text-sm text-muted-foreground">{category.count} reviews</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  </div>
);

const HowItWorksSection = () => (
  <div className="container px-4 md:px-6 mx-auto py-16">
    <div className="space-y-2 text-center mb-12">
      <h2 className="text-3xl font-bold tracking-tight">How ReviewsA2Z Works</h2>
      <p className="text-muted-foreground max-w-[700px] mx-auto">
        We leverage advanced AI to create unbiased, data-driven reviews
      </p>
    </div>
    
    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
      {[
        {
          title: "Data Collection",
          description: "Our AI gathers product specifications, customer feedback, and performance metrics from multiple sources.",
          icon: <Search className="h-8 w-8 text-primary" />,
        },
        {
          title: "AI Analysis",
          description: "Advanced algorithms analyze the data to identify strengths, weaknesses, and overall performance.",
          icon: <Bot className="h-8 w-8 text-primary" />,
        },
        {
          title: "Review Generation",
          description: "The AI creates a comprehensive, unbiased review with pros, cons, and detailed analysis.",
          icon: <Star className="h-8 w-8 text-primary" />,
        },
      ].map((step, i) => (
        <div 
          key={i}
          className="glass p-6 rounded-xl text-center transition-all duration-300 hover:shadow-md animate-fade-in"
          style={{ animationDelay: `${i * 200}ms` }}
        >
          <div className="mx-auto w-16 h-16 flex items-center justify-center rounded-full bg-primary/10 mb-4">
            {step.icon}
          </div>
          <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
          <p className="text-muted-foreground">{step.description}</p>
        </div>
      ))}
    </div>
    
    <div className="mt-12 text-center">
      <Button variant="outline" asChild>
        <Link to="/how-it-works">
          Learn More About Our Process <ChevronRight className="ml-2 h-5 w-5" />
        </Link>
      </Button>
    </div>
  </div>
);

const CtaSection = () => (
  <div className="bg-primary/5 py-16">
    <div className="container px-4 md:px-6 mx-auto">
      <div className="glass rounded-xl p-8 sm:p-12 relative overflow-hidden">
        {/* Background blurs */}
        <div className="absolute -bottom-16 -right-16 h-64 w-64 bg-primary/10 rounded-full blur-2xl"></div>
        <div className="absolute -top-16 -left-16 h-64 w-64 bg-blue-400/10 rounded-full blur-2xl"></div>
        
        <div className="relative z-10 max-w-3xl">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Ready to discover honest, AI-generated reviews?
          </h2>
          <p className="text-muted-foreground text-lg mb-8">
            Start exploring our extensive collection of unbiased product analyses and make informed decisions.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <Button size="lg" className="transition-all duration-300 hover:scale-[1.02]">
              <Search className="mr-2 h-5 w-5" /> Explore Reviews
            </Button>
            <Button variant="outline" size="lg">
              Join Our Community <CircleArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  </div>
);

const Index = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1">
        <HeroSection />
        <SearchSection />
        <FeaturedReviewsSection />
        <CategoriesSection />
        <HowItWorksSection />
        <CtaSection />
      </main>
      <Footer />
    </div>
  );
};

export default Index;
