import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Search, Shield, Bot } from 'lucide-react';
import { Input } from '@/components/ui/input';

const HeroSection = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const navigate = useNavigate();

  const handleSearch = (e?: React.FormEvent) => {
    if (e) {
      e.preventDefault();
    }
    if (searchQuery.trim()) {
      navigate(`/search?q=${encodeURIComponent(searchQuery.trim())}`);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleSearch();
    }
  };

  return (
    <div className="relative bg-gradient-to-b from-blue-50 to-transparent dark:from-gray-900 min-h-[90vh] flex items-center justify-center pb-8">
      <div className="text-center max-w-3xl mx-auto space-y-12">
        {/* Search Bar */}
        <div className="relative flex gap-2 max-w-2xl mx-auto">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Search for products, brands, or categories..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={handleKeyDown}
              className="pl-10 pr-4 w-full"
            />
          </div>
          <Button onClick={() => handleSearch()} size="icon" className="shrink-0">
            <Search className="h-4 w-4" />
          </Button>
        </div>

        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
            AI-Powered Reviews <br />
            <span className="text-primary">You Can Trust</span>
          </h1>
          <p className="text-muted-foreground md:text-xl">
            Discover unbiased, data-driven reviews generated by advanced AI. No human bias, just factual analysis.
          </p>
        </div>
        
        <div className="flex justify-center -space-x-1.5">
          <div className="h-7 w-7 rounded-full bg-primary/20 flex items-center justify-center">
            <Shield className="h-4 w-4 text-primary" />
          </div>
          <div className="h-7 w-7 rounded-full bg-primary/20 flex items-center justify-center">
            <Bot className="h-4 w-4 text-primary" />
          </div>
        </div>
        <p className="text-sm text-muted-foreground">
          Trusted by <span className="font-medium text-foreground">People Across the Globe</span>
        </p>
      </div>
    </div>
  );
};

export default HeroSection;
