
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge'; 
import { Search, ChevronRight, Star, Shield, Bot } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';

const HeroSection = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const navigate = useNavigate();

  const { data: latestReview, isLoading } = useQuery({
    queryKey: ['latestReview'],
    queryFn: async () => {
      console.log('Fetching latest review...');
      const { data, error } = await supabase
        .from('reviews')
        .select(`
          id, title, slug, image_url, rating, created_at
        `)
        .order('created_at', { ascending: false })
        .limit(1)
        .single();
        
      if (error) {
        console.error("Error fetching latest review:", error);
        return null;
      }
      
      console.log('Latest review fetched:', data);
      return data;
    },
    staleTime: 60000, // Cache for 1 minute
  });

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      navigate(`/search?q=${encodeURIComponent(searchQuery.trim())}`);
    }
  };

  return (
    <div className="relative bg-gradient-to-b from-blue-50 to-transparent dark:from-gray-900 min-h-[90vh] flex items-center">
      <div className="container px-4 md:px-6 mx-auto pt-32 pb-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-8 staggered-fade">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                AI-Powered Reviews <br />
                <span className="text-primary">You Can Trust</span>
              </h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl">
                Discover unbiased, data-driven reviews generated by advanced AI. No human bias, just factual analysis.
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="transition-all duration-300 hover:scale-[1.02] w-full h-14" asChild>
                <Link to="/search" className="w-full h-full flex items-center justify-center">
                  <Search className="mr-2 h-5 w-5" /> Explore Reviews
                </Link>
              </Button>
              <Button variant="outline" size="lg" className="w-full h-14" asChild>
                <Link to="/about" className="w-full h-full flex items-center justify-center">
                  How It Works <ChevronRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="flex -space-x-2">
                <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                  <Star className="h-5 w-5 text-primary" />
                </div>
                <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                  <Shield className="h-5 w-5 text-primary" />
                </div>
                <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center">
                  <Bot className="h-5 w-5 text-primary" />
                </div>
              </div>
              <p className="text-sm text-muted-foreground">
                Trusted by <span className="font-medium text-foreground">10,000+</span> users
              </p>
            </div>
          </div>
          
          {latestReview ? (
            <div className="relative">
              <div className="absolute -inset-0.5 bg-gradient-to-r from-primary to-blue-400 rounded-xl blur-xl"></div>
              <Link to={`/review/${latestReview.slug}`} className="block">
                <div className="relative glass rounded-xl overflow-hidden shadow-xl p-2 animate-fade-in hover:shadow-2xl transition-shadow duration-300">
                  <img 
                    src={latestReview.image_url || "https://images.unsplash.com/photo-1521791055366-0d553872125f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"} 
                    alt={latestReview.title} 
                    className="rounded-lg w-full h-full object-cover"
                  />
                  <div className="absolute bottom-0 left-0 right-0 glass p-4 backdrop-blur-md">
                    <div className="flex items-center justify-between">
                      <div>
                        <Badge className="mb-2">Latest Review</Badge>
                        <h3 className="font-medium">{latestReview.title}</h3>
                      </div>
                      <div className="flex text-yellow-400">
                        {[...Array(5)].map((_, i) => (
                          <Star key={i} className={`h-4 w-4 ${i < Math.round(latestReview.rating) ? 'fill-yellow-400' : 'text-gray-300'}`} />
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </Link>
            </div>
          ) : (
            isLoading ? (
              <div className="relative animate-pulse">
                <div className="bg-gray-200 dark:bg-gray-700 rounded-xl h-[300px]"></div>
              </div>
            ) : null
          )}
        </div>
      </div>
      
      <div className="hidden md:block absolute top-1/4 right-0 h-64 w-64 bg-primary/5 rounded-full blur-3xl"></div>
      <div className="hidden md:block absolute bottom-1/4 left-0 h-96 w-96 bg-blue-400/5 rounded-full blur-3xl"></div>
    </div>
  );
};

export default HeroSection;
