// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wucwtbxeandlvcfxipkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Y3d0YnhlYW5kbHZjZnhpcGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTU5OTUsImV4cCI6MjA1NjczMTk5NX0.KENTxS8cAC_pootgrIQDXh4kbJIrDX7uY5v-l2i9Voc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);